### Listar estudiantes
GET https://697828f05b9c0aed1e882a5d.mockapi.io/v1/students

### Crear un estudiando
POST https://697828f05b9c0aed1e882a5d.mockapi.io/v1/students
Content-Type: application/json

{
  "name": "Victor2",
  "city": "Chiclayo2"
}

### Actualizar los datos de un estudiante con su id
PUT https://697828f05b9c0aed1e882a5d.mockapi.io/v1/students/1
Content-Type: application/json

{
  "name": "Victor Actualizado",
  "city": "Chiclayo Actualizado"
}

### Eliminar un estudiante con su id
DELETE https://697828f05b9c0aed1e882a5d.mockapi.io/v1/students/2